##server:
##  port: 8082
##
##spring:
##  datasource:
##    url: jdbc:postgresql://localhost:5432/microservice
##    username: root
##    password: root
##jpa:
##  hibernate:
##    ddl-auto: update
##  show-sql: true
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/microservice
#    username: root
#    password: root
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
## Additional configuration
#server:
#  port: 8082
#
#
